/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#b7eaff",
        error: "#ba1a1a",
        outline: "#737686",
        "surface-variant": "#dae2fd",
        "on-secondary-container": "#006077",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#004e61",
        "on-surface": "#131b2e",
        "inverse-on-surface": "#eef0ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c0c1ff",
        "secondary-container": "#76dcff",
        "on-surface-variant": "#434655",
        "surface-container-high": "#e2e7ff",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#d2d9f4",
        "surface-container-highest": "#dae2fd",
        surface: "#faf8ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00174b",
        primary: "#004ac6",
        "surface-container": "#eaedff",
        "on-tertiary-container": "#f1eeff",
        "primary-fixed-dim": "#b4c5ff",
        tertiary: "#3e3fcc",
        background: "#faf8ff",
        "outline-variant": "#c3c6d7",
        "inverse-primary": "#b4c5ff",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed-dim": "#6cd3f7",
        secondary: "#006780",
        "on-tertiary-fixed": "#07006c",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-container": "#585be6",
        "on-error-container": "#93000a",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#001f28",
        "primary-container": "#2563eb",
        "error-container": "#ffdad6",
        "surface-tint": "#0053db",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "on-primary-fixed-variant": "#003ea8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-sm": "1rem",
        margin: "2rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-sm": "1rem",
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
